version: '3.9'

services:
  app:
    build: .
    container_name: fastapi_blueprint
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONPATH=/app
